# Generated by Django 5.0.7 on 2024-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='nombre',
            field=models.CharField(max_length=260),
        ),
    ]
