# Generated by Django 5.0.7 on 2024-08-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrganic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img_production/')),
                ('titulo', models.CharField(max_length=220)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
